export const DEFAULT_STATE = {
  nameFlag: false,
  nameValue: "",
  lastNameFlag: false,
  lastNameValue: "",
  dateValue: "",
  phoneFlag: false,
  phoneValue: "",
  siteFlag: false,
  siteValue: "",
  emptyMessage: "Cannot be empty",
  aboutAreaValue: "",
  aboutAreaFlag: false,
  stackAreaValue: "",
  stackAreaFlag: false,
  projectAreaValue: "",
  projectAreaFlag: false,
  modalActive: false,
  formInvalid: false,
}